name: "CI for Core"

on:
  pull_request:
    paths:
      - 'infra/**'
      - 'api/**'

jobs:
  terraform-plan:
    permissions:
      id-token: write
      contents: read
    uses: kitsune242/aws-common/.github/workflows/terraform.yml@v1.0.0
    secrets: inherit
    with:
      path: "infra"
      env: dev
      action: "plan"
      common_ref: "v1.0.0"
